<link href="<c:url value='/static/css/bootstrap.min.css'/>" rel="stylesheet" type="text/css">
<link href="<c:url value='/static/css/bootstrap-table.css'/>" rel="stylesheet" type="text/css">
<link href="<c:url value='/static/css/sweetalert/sweetalert.css'/>" rel="stylesheet" type="text/css">
<link href="<c:url value='/static/css/datepicker/datepicker.css'/>" rel="stylesheet" type="text/css">
<link href="<c:url value='/static/css/datepicker/bootstrap-datetimepicker.min.css'/>" rel="stylesheet" type="text/css">

