<script type="text/javascript" src="<c:url value='/static/js/jquery.min.js'/>"></script>
<script type="text/javascript" src="<c:url value='/static/js/jquery.validate.js'/>"></script>
<script type="text/javascript" src="<c:url value='/static/js/bootstrap.min.js'/>"></script>
<script type="text/javascript" src="<c:url value='/static/js/bootstrap-table/bootstrap-table.js'/>"></script>
<script type="text/javascript" src="<c:url value='/static/js/sweetalert/sweetalert.min.js'/>"></script>
<script type="text/javascript" src="<c:url value='/static/js/datepicker/bootstrap-datepicker.js'/>"></script>
<script type="text/javascript" src="<c:url value='/static/js/bootstrap-table/bootstrap-table-zh-CN.js'/>"></script>

